### ISSUE TITLE
Rviz2 Malformed STL error

### ISSUE THREAD

**Issue by roni-kreinin** [turtlebot/turtlebot4_desktop#1]
- OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: source

 **Expected behaviour**
Launching view_model.launch.py or view_robot.launch.py should show the model with correct mesh colours.

 **Actual behaviour**
 Turtlebot4 components are shown in red, Rviz logs the following error:
`The STL file '*.STL' is malformed. It starts with the word 'solid', indicating that it's an ASCII STL file, but it does not contain the word 'endsolid' so it is either a malformed ASCII STL file or it is actually a binary STL file. Trying to interpret it as a binary STL file instead.`

**To Reproduce**
Provide the steps to reproduce:
`ros2 launch turtlebot4_viz view_model.launch.py description:=true`

**Other notes**
Online solutions such as https://gist.github.com/awesomebytes/2595b1dc41831c804a4f have not worked.

**Comment by ranjitkathiriya** [comment]
Hello Roni,

How did you solved this issue?

**Comment by JSOV2001** [comment]
> Hello Roni,
> 
> How did you solved this issue?

Hi, 

https://gist.github.com/awesomebytes/2595b1dc41831c804a4f

The solution Roni mentioned actually did work for me. I hope It does the same for you
